name: Jaspr Web
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - run: dart pub get
      - run: dart run jaspr_cli build
      - run: echo ezorr.io > build/jaspr/CNAME
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/jaspr'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
